In [200]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
1. Perfil Demográfico
-(EDAD)Age: Edad del usuario (útil para ver qué generaciones prefieren qué contenido).
-(GENERO)Gender: Género (vimos que influye mucho en el volumen de escucha nocturna).
2. Relación con Spotify
-(ANTIGUEDAD)spotify_usage_period: Antigüedad del usuario (¿es nuevo o lleva años?).
-(DISPOSITIVO)spotify_listening_device: Dispositivo principal (Smartphone, Computer, etc.). Clave para predecir si pagarán.
-(SUSCRIPCION)spotify_subscription_plan: Si es usuario Free o Premium actualmente.
-(QUIERE_PREMIUM)premium_sub_willingness: ¿Está dispuesto a pagar? (Tu variable objetivo para el modelo de ML).
-(PREMIUM_PREFERIDO)preffered_premium_plan: Qué plan le atrae más (Individual, Duo, Familiar) y  cúanto estás dispuesto a pagar.
3. Hábitos Musicales
-(CONTENIDO_PREFERIDO)preferred_listening_content: Si prefiere solo música, solo podcasts o ambos.
-(GENERO_FAVORITO_MUSICA)fav_music_genre: Su género favorito (Pop, Rock, Rap, etc.).
-(FRANJA_HORARIA)music_time_slot: En qué momento del día escucha más (Tu famoso "Prime Time").
-(ESTADO_ANIMO)-music_Influencial_mood: Qué estado de ánimo le impulsa a escuchar música (Tristeza, felicidad, estudio).
-(MOMENTO_MUSICA)music_lis_frequency: Con qué frecuencia escucha música (Diario, semanal, etc.).
-(DESCUBRIMIENTO)music_expl_method: Cómo descubre canciones nuevas (Playlists, radio, amigos).
-(VALORACION_RECOMENDACIONES)music_recc_rating: Qué tan buenas cree que son las recomendaciones de Spotify (Escala 1-5).
4. Hábitos de Podcasts
-(FRECUENCIA_POD)pod_lis_frequency: Frecuencia de escucha de podcasts.
-(GENERO_FAVORITO_POD)fav_pod_genre: Géneros preferidos (Comedia, True Crime, etc.).
-(FORMATO_PREFERIDO_POD)preffered_pod_format: Si prefiere entrevistas, narrativas o monólogos.
-(PREFERENCIA_PRESENTADOR_POD)pod_host_preference: Si sigue a hosts famosos o le da igual quién hable.
-(PREFERENCIA_DURACION_POD)preffered_pod_duration: Cuánto tiempo quiere que duren los episodios.
-(SATISFACCION_POD)pod_variety_satisfaction: Nivel de satisfacción con la variedad de podcasts (Escala 1-5).
-(CONSUME_POD)= Columna (creada por nosotras) de True/False sobre quién consume podcast o no

In [ ]:
***********************************************************************************************************************

In [324]:
#https://www.kaggle.com/datasets/meeraajayakumar/spotify-user-behavior-dataset/data
ruta = r'C:\Users\palom\OneDrive\Escritorio\SPOTYFY\Spotify_data.xlsx'
Spotify_data = pd.read_excel(ruta)
Spotify_data

,Age,Gender,spotify_usage_period,spotify_listening_device,spotify_subscription_plan,premium_sub_willingness,preffered_premium_plan,preferred_listening_content,fav_music_genre,music_time_slot,music_Influencial_mood,music_lis_frequency,music_expl_method,music_recc_rating,pod_lis_frequency,fav_pod_genre,preffered_pod_format,pod_host_preference,preffered_pod_duration,pod_variety_satisfaction
0,20-35,Female,More than 2 years,Smart speakers or voice assistants,Free (ad-supported),Yes,Family Plan-Rs 179/month,Podcast,Melody,Night,Sadness or melancholy,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Male,More than 2 years,Computer or laptop,Free (ad-supported),Yes,Individual Plan- Rs 119/ month,Podcast,Rap,Afternoon,Social gatherings or parties,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Others,6 months to 1 year,Smart speakers or voice assistants,Free (ad-supported),Yes,Student Plan-Rs 59/month,Podcast,Pop,Night,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Female,1 year to 2 years,"Smartphone, Smart speakers or voice assistants",Free (ad-supported),No,NaN,Music,Melody,Night,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Female,1 year to 2 years,Smartphone,Free (ad-supported),No,NaN,Music,Melody,Night,Relaxation and stress relief,leisure time,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,20-35,Female,More than 2 years,"Smartphone, Computer or laptop, Wearable devices",Free (ad-supported),Yes,Student Plan-Rs 59/month,Music,Pop,Morning,"Uplifting and motivational, Sadness or melancholy",While Traveling,recommendations,5,Rarely,Lifestyle and Health,Conversational,Both,Shorter,Ok
516,20-35,Female,More than 2 years,"Smartphone, Computer or laptop",Free (ad-supported),Yes,Student Plan-Rs 59/month,Music,Pop,Night,"Relaxation and stress relief, Uplifting and mo...","While Traveling, Workout session, leisure time",Others,2,Rarely,Comedy,Story telling,Both,Shorter,Ok
517,20-35,Female,More than 2 years,Smartphone,Free (ad-supported),No,Student Plan-Rs 59/month,Music,Pop,Night,Relaxation and stress relief,leisure time,recommendations,3,Never,NaN,Story telling,Both,Shorter,Ok
518,20-35,Female,6 months to 1 year,Smartphone,Premium (paid subscription),Yes,Individual Plan- Rs 119/ month,Music,Melody,Night,"Relaxation and stress relief, Uplifting and mo...","Workout session, leisure time","recommendations, Others",2,Several times a week,Comedy,Conversational,Both,Longer,Satisfied
519,20-35,Female,More than 2 years,"Smartphone, Computer or laptop",Premium (paid subscription),Yes,Student Plan-Rs 59/month,Music,Pop,Night,"Relaxation and stress relief, Sadness or melan...","Office hours,Study Hours, While Traveling, lei...","Playlists, Radio",3,Never,NaN,NaN,NaN,NaN,Ok

In [203]:
nuevos_nombres = {
    'Age': 'EDAD',
    'Gender': 'GENERO',
    'spotify_usage_period': 'ANTIGUEDAD',
    'spotify_listening_device': 'DISPOSITIVO',
    'spotify_subscription_plan': 'SUSCRIPCION',
    'premium_sub_willingness': 'QUIERE_PREMIUM',
    'preffered_premium_plan': 'PREMIUM_PREFERIDO',
    'preferred_listening_content': 'CONTENIDO_PREFERIDO',
    'fav_music_genre': 'GENERO_FAV_MUSICA',
    'music_time_slot': 'FRANJA_HORARIA',
    'music_Influencial_mood': 'ESTADO_ANIMO',
    'music_lis_frequency': 'MOMENTO_MUSICA',
    'music_expl_method': 'DESCUBRIMIENTO',
    'music_recc_rating': 'VALORACION_RECOMENDACIONES',
    'pod_lis_frequency': 'FRECUENCIA_POD',
    'fav_pod_genre': 'GENERO_FAV_POD',
    'preffered_pod_format': 'FORMATO_PREFERIDO_POD',
    'pod_host_preference': 'PREFERENCIA_PRESENTADOR_POD',
    'preffered_pod_duration': 'PREFERENCIA_DURACION_POD',
    'pod_variety_satisfaction': 'SATISFACCION_POD'
}


Spotify_data = Spotify_data.rename(columns=nuevos_nombres)


print(Spotify_data.columns)
Spotify_data.head()

Index(['EDAD', 'GENERO', 'ANTIGUEDAD', 'DISPOSITIVO', 'SUSCRIPCION',
       'QUIERE_PREMIUM', 'PREMIUM_PREFERIDO', 'CONTENIDO_PREFERIDO',
       'GENERO_FAV_MUSICA', 'FRANJA_HORARIA', 'ESTADO_ANIMO', 'MOMENTO_MUSICA',
       'DESCUBRIMIENTO', 'VALORACION_RECOMENDACIONES', 'FRECUENCIA_POD',
       'GENERO_FAV_POD', 'FORMATO_PREFERIDO_POD',
       'PREFERENCIA_PRESENTADOR_POD', 'PREFERENCIA_DURACION_POD',
       'SATISFACCION_POD'],
      dtype='object')

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Female,More than 2 years,Smart speakers or voice assistants,Free (ad-supported),Yes,Family Plan-Rs 179/month,Podcast,Melody,Night,Sadness or melancholy,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Male,More than 2 years,Computer or laptop,Free (ad-supported),Yes,Individual Plan- Rs 119/ month,Podcast,Rap,Afternoon,Social gatherings or parties,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Others,6 months to 1 year,Smart speakers or voice assistants,Free (ad-supported),Yes,Student Plan-Rs 59/month,Podcast,Pop,Night,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Female,1 year to 2 years,"Smartphone, Smart speakers or voice assistants",Free (ad-supported),No,NaN,Music,Melody,Night,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Female,1 year to 2 years,Smartphone,Free (ad-supported),No,NaN,Music,Melody,Night,Relaxation and stress relief,leisure time,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [204]:
nuevos_nombres_genero = {
    'Female': 'Mujer',
    'Male': 'Hombre',
    'Others': 'Otro'
    }
Spotify_data['GENERO'] = Spotify_data['GENERO'].replace(nuevos_nombres_genero)

print(Spotify_data['GENERO'].unique())
Spotify_data.head()

['Mujer' 'Hombre' 'Otro']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,More than 2 years,Smart speakers or voice assistants,Free (ad-supported),Yes,Family Plan-Rs 179/month,Podcast,Melody,Night,Sadness or melancholy,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Hombre,More than 2 years,Computer or laptop,Free (ad-supported),Yes,Individual Plan- Rs 119/ month,Podcast,Rap,Afternoon,Social gatherings or parties,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Otro,6 months to 1 year,Smart speakers or voice assistants,Free (ad-supported),Yes,Student Plan-Rs 59/month,Podcast,Pop,Night,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Mujer,1 year to 2 years,"Smartphone, Smart speakers or voice assistants",Free (ad-supported),No,NaN,Music,Melody,Night,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,1 year to 2 years,Smartphone,Free (ad-supported),No,NaN,Music,Melody,Night,Relaxation and stress relief,leisure time,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [205]:
Spotify_data["ANTIGUEDAD"].unique()

array(['More than 2 years', '6 months to 1 year', '1 year to 2 years',
       'Less than 6 months'], dtype=object)

In [206]:
nuevos_nombres_antiguedad = {
    'More than 2 years':'Más de 2 años', 
    '6 months to 1 year':'De 6 meses a 1 año',
    '1 year to 2 years':'De 1 año a 2 años',
    'Less than 6 months':'Menos de 6 meses'
    }
Spotify_data['ANTIGUEDAD'] = Spotify_data['ANTIGUEDAD'].replace(nuevos_nombres_antiguedad)

print(Spotify_data['ANTIGUEDAD'].unique())
Spotify_data.head()

['Más de 2 años' 'De 6 meses a 1 año' 'De 1 año a 2 años'
 'Menos de 6 meses']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Smart speakers or voice assistants,Free (ad-supported),Yes,Family Plan-Rs 179/month,Podcast,Melody,Night,Sadness or melancholy,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Hombre,Más de 2 años,Computer or laptop,Free (ad-supported),Yes,Individual Plan- Rs 119/ month,Podcast,Rap,Afternoon,Social gatherings or parties,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Smart speakers or voice assistants,Free (ad-supported),Yes,Student Plan-Rs 59/month,Podcast,Pop,Night,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Smart speakers or voice assistants",Free (ad-supported),No,NaN,Music,Melody,Night,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free (ad-supported),No,NaN,Music,Melody,Night,Relaxation and stress relief,leisure time,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [207]:
Spotify_data["DISPOSITIVO"].unique()

array(['Smart speakers or voice assistants', 'Computer or laptop',
       'Smartphone, Smart speakers or voice assistants', 'Smartphone',
       'Smartphone, Computer or laptop',
       'Smartphone, Computer or laptop, Smart speakers or voice assistants',
       'Smartphone, Wearable devices',
       'Smartphone, Computer or laptop, Wearable devices',
       'Computer or laptop, Wearable devices',
       'Smartphone, Computer or laptop, Smart speakers or voice assistants, Wearable devices',
       'Wearable devices',
       'Smartphone, Smart speakers or voice assistants, Wearable devices',
       'Computer or laptop, Smart speakers or voice assistants',
       'Computer or laptop, Smart speakers or voice assistants, Wearable devices',
       'Smart speakers or voice assistants, Wearable devices'],
      dtype=object)

In [208]:
nuevos_nombres_dispositivo = {
    'Smart speakers or voice assistants':'Altavoz Inteligente',
    'Computer or laptop':'Ordenador',
    'Smartphone, Smart speakers or voice assistants':'Smartphone, Altavoz Inteligente',
    'Smartphone':'Smartphone',
    'Smartphone, Computer or laptop':'Smartphone, Ordenador',
    'Smartphone, Computer or laptop, Smart speakers or voice assistants':'Smartphone, Ordenador, Altavoz Inteligente',
    'Smartphone, Wearable devices':'Smartphone, Dispositivo Portatil Inteligente',
    'Smartphone, Computer or laptop, Wearable devices':'Smartphone, Ordenador, Dispositivo Portatil Inteligente',
    'Computer or laptop, Wearable devices':'Ordenador, Dispositivo Portatil Inteligente',
    'Smartphone, Computer or laptop, Smart speakers or voice assistants, Wearable devices':'Smartphone, Ordenador, Altavoz Inteligente, Dispositivo Portatil Inteligente',
    'Wearable devices':'Dispositivo Portatil Inteligente',
    'Smartphone, Smart speakers or voice assistants, Wearable devices':'Smartphone, Altavoz Inteligente, Dispositivo Portatil Inteligente',
    'Computer or laptop, Smart speakers or voice assistants':'Ordenador, Altavoz Inteligente',
    'Computer or laptop, Smart speakers or voice assistants, Wearable devices':'Ordenador, Altavoz Inteligente, Dispositivo Portatil Inteligente',
    'Smart speakers or voice assistants, Wearable devices':'Altavoz Inteligente, Dispositivo Portatil Inteligente' 
    }
Spotify_data['DISPOSITIVO'] = Spotify_data['DISPOSITIVO'].replace(nuevos_nombres_dispositivo)

print(Spotify_data['DISPOSITIVO'].unique())
Spotify_data.head()

['Altavoz Inteligente' 'Ordenador' 'Smartphone, Altavoz Inteligente'
 'Smartphone' 'Smartphone, Ordenador'
 'Smartphone, Ordenador, Altavoz Inteligente'
 'Smartphone, Dispositivo Portatil Inteligente'
 'Smartphone, Ordenador, Dispositivo Portatil Inteligente'
 'Ordenador, Dispositivo Portatil Inteligente'
 'Smartphone, Ordenador, Altavoz Inteligente, Dispositivo Portatil Inteligente'
 'Dispositivo Portatil Inteligente'
 'Smartphone, Altavoz Inteligente, Dispositivo Portatil Inteligente'
 'Ordenador, Altavoz Inteligente'
 'Ordenador, Altavoz Inteligente, Dispositivo Portatil Inteligente'
 'Altavoz Inteligente, Dispositivo Portatil Inteligente']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free (ad-supported),Yes,Family Plan-Rs 179/month,Podcast,Melody,Night,Sadness or melancholy,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free (ad-supported),Yes,Individual Plan- Rs 119/ month,Podcast,Rap,Afternoon,Social gatherings or parties,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free (ad-supported),Yes,Student Plan-Rs 59/month,Podcast,Pop,Night,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free (ad-supported),No,NaN,Music,Melody,Night,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free (ad-supported),No,NaN,Music,Melody,Night,Relaxation and stress relief,leisure time,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [209]:
Spotify_data["SUSCRIPCION"].unique()

array(['Free (ad-supported)', 'Premium (paid subscription)'], dtype=object)

In [210]:
nuevos_nombres_suscripcion = {
    'Free (ad-supported)':'Free',
    'Premium (paid subscription)':'Premium'}

Spotify_data['SUSCRIPCION'] = Spotify_data['SUSCRIPCION'].replace(nuevos_nombres_suscripcion)

print(Spotify_data['SUSCRIPCION'].unique())
Spotify_data.head()

['Free' 'Premium']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Yes,Family Plan-Rs 179/month,Podcast,Melody,Night,Sadness or melancholy,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Yes,Individual Plan- Rs 119/ month,Podcast,Rap,Afternoon,Social gatherings or parties,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Yes,Student Plan-Rs 59/month,Podcast,Pop,Night,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,NaN,Music,Melody,Night,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,NaN,Music,Melody,Night,Relaxation and stress relief,leisure time,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [211]:
Spotify_data["QUIERE_PREMIUM"].unique()

array(['Yes', 'No'], dtype=object)

In [212]:
nuevos_nombres_quiere_premium = {
    'Yes':'Si'}

Spotify_data['QUIERE_PREMIUM'] = Spotify_data['QUIERE_PREMIUM'].replace(nuevos_nombres_quiere_premium)

print(Spotify_data['QUIERE_PREMIUM'].unique())
Spotify_data.head()

['Si' 'No']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Si,Family Plan-Rs 179/month,Podcast,Melody,Night,Sadness or melancholy,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Si,Individual Plan- Rs 119/ month,Podcast,Rap,Afternoon,Social gatherings or parties,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Si,Student Plan-Rs 59/month,Podcast,Pop,Night,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,NaN,Music,Melody,Night,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,NaN,Music,Melody,Night,Relaxation and stress relief,leisure time,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [213]:
Spotify_data["FRANJA_HORARIA"].unique()

array(['Night', 'Afternoon', 'Morning'], dtype=object)

In [214]:
nuevos_nombres_horario = {
    'Night':'Noche',
    'Afternoon':'Tarde',
    'Morning':'Mañana'
}

Spotify_data['FRANJA_HORARIA'] = Spotify_data['FRANJA_HORARIA'].replace(nuevos_nombres_horario)

print(Spotify_data['FRANJA_HORARIA'].unique())
Spotify_data.head()

['Noche' 'Tarde' 'Mañana']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Si,Family Plan-Rs 179/month,Podcast,Melody,Noche,Sadness or melancholy,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Si,Individual Plan- Rs 119/ month,Podcast,Rap,Tarde,Social gatherings or parties,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Si,Student Plan-Rs 59/month,Podcast,Pop,Noche,Relaxation and stress relief,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,NaN,Music,Melody,Noche,"Relaxation and stress relief, Social gathering...","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,NaN,Music,Melody,Noche,Relaxation and stress relief,leisure time,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [215]:
Spotify_data["ESTADO_ANIMO"].unique()

array(['Sadness or melancholy', 'Social gatherings or parties',
       'Relaxation and stress relief',
       'Relaxation and stress relief, Social gatherings or parties',
       'Uplifting and motivational',
       'Relaxation and stress relief, Uplifting and motivational',
       'Relaxation and stress relief, Uplifting and motivational, Sadness or melancholy, Social gatherings or parties',
       'Relaxation and stress relief, Sadness or melancholy',
       'Relaxation and stress relief, Uplifting and motivational, Social gatherings or parties',
       'Relaxation and stress relief, Uplifting and motivational, Sadness or melancholy',
       'Uplifting and motivational, Sadness or melancholy',
       'Relaxation and stress relief, Sadness or melancholy, Social gatherings or parties',
       'Sadness or melancholy, Social gatherings or parties',
       'Uplifting and motivational, Sadness or melancholy, Social gatherings or parties',
       'Uplifting and motivational, Social gatherings or parties'],
      dtype=object)

In [216]:
nuevos_nombres_animo = {
    'Sadness or melancholy':'Tristeza', 
    'Social gatherings or parties':'Reuniones Sociales',
    'Relaxation and stress relief':'Relajación',
    'Relaxation and stress relief, Social gatherings or parties':'Relajación, Reuniones Sociales',
    'Uplifting and motivational':'Motivador',
    'Relaxation and stress relief, Uplifting and motivational':'Relajación, Motivador',
    'Relaxation and stress relief, Uplifting and motivational, Sadness or melancholy, Social gatherings or parties':'Relajación, Motivador, Tristeza, Reuniones Sociales',
    'Relaxation and stress relief, Sadness or melancholy':'Relajación, Tristeza',
    'Relaxation and stress relief, Uplifting and motivational, Social gatherings or parties':'Relajación, Motivador, Reuniones Sociales',
    'Relaxation and stress relief, Uplifting and motivational, Sadness or melancholy':'Relajación, Motivador, Tristeza',
    'Uplifting and motivational, Sadness or melancholy':'Motivador, Tristeza',
    'Relaxation and stress relief, Sadness or melancholy, Social gatherings or parties':'Relajación, Tristeza, Reuniones Sociales',
    'Sadness or melancholy, Social gatherings or parties':'Tristeza, Reuniones Sociales',
    'Uplifting and motivational, Sadness or melancholy, Social gatherings or parties':'Motivador, Tristeza, Reuniones Sociales',
    'Uplifting and motivational, Social gatherings or parties':'Motivador, Reuniones Sociales'
}

Spotify_data['ESTADO_ANIMO'] = Spotify_data['ESTADO_ANIMO'].replace(nuevos_nombres_animo)

print(Spotify_data['ESTADO_ANIMO'].unique())
Spotify_data.head()

['Tristeza' 'Reuniones Sociales' 'Relajación'
 'Relajación, Reuniones Sociales' 'Motivador' 'Relajación, Motivador'
 'Relajación, Motivador, Tristeza, Reuniones Sociales'
 'Relajación, Tristeza' 'Relajación, Motivador, Reuniones Sociales'
 'Relajación, Motivador, Tristeza' 'Motivador, Tristeza'
 'Relajación, Tristeza, Reuniones Sociales' 'Tristeza, Reuniones Sociales'
 'Motivador, Tristeza, Reuniones Sociales' 'Motivador, Reuniones Sociales']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Si,Family Plan-Rs 179/month,Podcast,Melody,Noche,Tristeza,leisure time,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Si,Individual Plan- Rs 119/ month,Podcast,Rap,Tarde,Reuniones Sociales,Workout session,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Si,Student Plan-Rs 59/month,Podcast,Pop,Noche,Relajación,"Study Hours, While Traveling",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,NaN,Music,Melody,Noche,"Relajación, Reuniones Sociales","Office hours, Workout session, leisure time","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,NaN,Music,Melody,Noche,Relajación,leisure time,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [217]:
Spotify_data["MOMENTO_MUSICA"].unique()

array(['leisure time', 'Workout session', 'Study Hours, While Traveling',
       'Office hours, Workout session, leisure time', 'Office hours',
       'While Traveling, leisure time',
       'Office hours, While Traveling, Workout session',
       'Office hours, While Traveling',
       'Office hours, While Traveling, leisure time',
       'Social gatherings ', 'While Traveling',
       'While Traveling, Workout session, leisure time', 'Study Hours',
       'Study Hours, leisure time', 'While Traveling, Workout session',
       'Study Hours, Workout session, leisure time',
       'Office hours, While Traveling, ', 'Workout session, leisure time',
       'While Traveling, Workout session, leisure time, Night time, when cooking',
       'Office hours, While Traveling, Workout session, leisure time',
       'Study Hours, While Traveling, Workout session, leisure time',
       'Office hours, Study Hours, While Traveling, Workout session, leisure time',
       'Office hours, leisure time', 'Study Hours, Workout session',
       'Office hours, Study Hours, While Traveling, leisure time',
       'Study Hours, While Traveling, leisure time',
       'Office hours, Workout session',
       'Office hours, Study Hours, While Traveling', 'Random ',
       'Study Hours, While Traveling, Workout session',
       'Office hours, Study Hours, Workout session',
       'While Traveling, Before bed ',
       'Office hours, Study Hours, While Traveling, Workout session',
       'Office hours, Study Hours, While Traveling, Workout session, leisure time, ',
       'Office hours,Study Hours, While Traveling, leisure time'],
      dtype=object)

In [218]:
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace("leisure time", "Tiempo libre", regex=False)
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace("Workout session", "Entrenamiento", regex=False)
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace("Study Hours", "Horas de estudio", regex=False)
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace("While Traveling", "Mientras viaja", regex=False)
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace("Office hours", "Horario de oficina", regex=False)
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace("Social gatherings", "Reuniones sociales", regex=False)
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace("Night time", "Por la noche", regex=False)
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace("when cooking", "Cocinando", regex=False)
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace("Random", "Aleatorio", regex=False)
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace("Before bed", "Antes de dormir", regex=False)

# Limpieza básica
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.strip()
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace(", ,", ",", regex=False)
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.replace(",,", ",", regex=False)
Spotify_data["MOMENTO_MUSICA"] = Spotify_data["MOMENTO_MUSICA"].str.rstrip(", ")

# Comprobar
print(Spotify_data["MOMENTO_MUSICA"].nunique())
print(Spotify_data["MOMENTO_MUSICA"].unique())

33
['Tiempo libre' 'Entrenamiento' 'Horas de estudio, Mientras viaja'
 'Horario de oficina, Entrenamiento, Tiempo libre' 'Horario de oficina'
 'Mientras viaja, Tiempo libre'
 'Horario de oficina, Mientras viaja, Entrenamiento'
 'Horario de oficina, Mientras viaja'
 'Horario de oficina, Mientras viaja, Tiempo libre' 'Reuniones sociales'
 'Mientras viaja' 'Mientras viaja, Entrenamiento, Tiempo libre'
 'Horas de estudio' 'Horas de estudio, Tiempo libre'
 'Mientras viaja, Entrenamiento'
 'Horas de estudio, Entrenamiento, Tiempo libre'
 'Entrenamiento, Tiempo libre'
 'Mientras viaja, Entrenamiento, Tiempo libre, Por la noche, Cocinando'
 'Horario de oficina, Mientras viaja, Entrenamiento, Tiempo libre'
 'Horas de estudio, Mientras viaja, Entrenamiento, Tiempo libre'
 'Horario de oficina, Horas de estudio, Mientras viaja, Entrenamiento, Tiempo libre'
 'Horario de oficina, Tiempo libre' 'Horas de estudio, Entrenamiento'
 'Horario de oficina, Horas de estudio, Mientras viaja, Tiempo libre'
 'Horas de estudio, Mientras viaja, Tiempo libre'
 'Horario de oficina, Entrenamiento'
 'Horario de oficina, Horas de estudio, Mientras viaja' 'Aleatorio'
 'Horas de estudio, Mientras viaja, Entrenamiento'
 'Horario de oficina, Horas de estudio, Entrenamiento'
 'Mientras viaja, Antes de dormir'
 'Horario de oficina, Horas de estudio, Mientras viaja, Entrenamiento'
 'Horario de oficina,Horas de estudio, Mientras viaja, Tiempo libre']

In [221]:
Spotify_data.head()

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Si,Family Plan-Rs 179/month,Podcast,Melody,Noche,Tristeza,Tiempo libre,Playlists,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Si,Individual Plan- Rs 119/ month,Podcast,Rap,Tarde,Reuniones Sociales,Entrenamiento,Playlists,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Si,Student Plan-Rs 59/month,Podcast,Pop,Noche,Relajación,"Horas de estudio, Mientras viaja",Playlists,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,NaN,Music,Melody,Noche,"Relajación, Reuniones Sociales","Horario de oficina, Entrenamiento, Tiempo libre","recommendations, Playlists",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,NaN,Music,Melody,Noche,Relajación,Tiempo libre,"recommendations, Playlists",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [222]:
Spotify_data["DESCUBRIMIENTO"].unique()

array(['Playlists', 'recommendations, Playlists', 'Others',
       'recommendations', 'Playlists, Radio', 'recommendations, Others',
       'recommendations, Playlists, Radio', 'recommendations, Radio',
       'recommendations, Playlists, Others', 'Radio', 'Radio, Others',
       'Playlists, Others', 'Playlists, Radio, Others',
       'recommendations, Radio, Others',
       'recommendations,Others, Social media', 'Others, Social media',
       'recommendations, Playlists, Radio, Others', 'Others, Friends',
       'recommendations, Others, Social media', 'Others, Search'],
      dtype=object)

In [223]:
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.replace("Playlists", "Listas de reproducción", regex=False)
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.replace("recommendations", "Recomendaciones", regex=False)
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.replace("Radio", "Radio", regex=False)
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.replace("Others", "Otros", regex=False)
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.replace("Social media", "Redes sociales", regex=False)
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.replace("Friends", "Amigos", regex=False)
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.replace("Search", "Búsqueda", regex=False)

# Limpieza básica de espacios/comas
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.strip()
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.replace(",Others", ", Otros", regex=False)
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.replace(" ,", ",", regex=False)
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.replace(", ,", ",", regex=False)
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.replace(",,", ",", regex=False)
Spotify_data["DESCUBRIMIENTO"] = Spotify_data["DESCUBRIMIENTO"].str.rstrip(", ")

# Comprobar
print(Spotify_data["DESCUBRIMIENTO"].unique())
print("Nº valores únicos:", Spotify_data["DESCUBRIMIENTO"].nunique())

['Listas de reproducción' 'Recomendaciones, Listas de reproducción'
 'Otros' 'Recomendaciones' 'Listas de reproducción, Radio'
 'Recomendaciones, Otros' 'Recomendaciones, Listas de reproducción, Radio'
 'Recomendaciones, Radio' 'Recomendaciones, Listas de reproducción, Otros'
 'Radio' 'Radio, Otros' 'Listas de reproducción, Otros'
 'Listas de reproducción, Radio, Otros' 'Recomendaciones, Radio, Otros'
 'Recomendaciones,Otros, Redes sociales' 'Otros, Redes sociales'
 'Recomendaciones, Listas de reproducción, Radio, Otros' 'Otros, Amigos'
 'Recomendaciones, Otros, Redes sociales' 'Otros, Búsqueda']
Nº valores únicos: 20

In [224]:
Spotify_data

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Si,Family Plan-Rs 179/month,Podcast,Melody,Noche,Tristeza,Tiempo libre,Listas de reproducción,3,Daily,Comedy,Interview,Both,Both,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Si,Individual Plan- Rs 119/ month,Podcast,Rap,Tarde,Reuniones Sociales,Entrenamiento,Listas de reproducción,2,Several times a week,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Si,Student Plan-Rs 59/month,Podcast,Pop,Noche,Relajación,"Horas de estudio, Mientras viaja",Listas de reproducción,4,Once a week,Sports,Interview,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,NaN,Music,Melody,Noche,"Relajación, Reuniones Sociales","Horario de oficina, Entrenamiento, Tiempo libre","Recomendaciones, Listas de reproducción",4,Never,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,NaN,Music,Melody,Noche,Relajación,Tiempo libre,"Recomendaciones, Listas de reproducción",4,Rarely,Lifestyle and Health,Story telling,Well known individuals,Both,Ok
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,20-35,Mujer,Más de 2 años,"Smartphone, Ordenador, Dispositivo Portatil In...",Free,Si,Student Plan-Rs 59/month,Music,Pop,Mañana,"Motivador, Tristeza",Mientras viaja,Recomendaciones,5,Rarely,Lifestyle and Health,Conversational,Both,Shorter,Ok
516,20-35,Mujer,Más de 2 años,"Smartphone, Ordenador",Free,Si,Student Plan-Rs 59/month,Music,Pop,Noche,"Relajación, Motivador, Tristeza, Reuniones Soc...","Mientras viaja, Entrenamiento, Tiempo libre",Otros,2,Rarely,Comedy,Story telling,Both,Shorter,Ok
517,20-35,Mujer,Más de 2 años,Smartphone,Free,No,Student Plan-Rs 59/month,Music,Pop,Noche,Relajación,Tiempo libre,Recomendaciones,3,Never,NaN,Story telling,Both,Shorter,Ok
518,20-35,Mujer,De 6 meses a 1 año,Smartphone,Premium,Si,Individual Plan- Rs 119/ month,Music,Melody,Noche,"Relajación, Motivador","Entrenamiento, Tiempo libre","Recomendaciones, Otros",2,Several times a week,Comedy,Conversational,Both,Longer,Satisfied
519,20-35,Mujer,Más de 2 años,"Smartphone, Ordenador",Premium,Si,Student Plan-Rs 59/month,Music,Pop,Noche,"Relajación, Tristeza","Horario de oficina,Horas de estudio, Mientras ...","Listas de reproducción, Radio",3,Never,NaN,NaN,NaN,NaN,Ok

In [225]:
Spotify_data["FRECUENCIA_POD"].unique()

array(['Daily', 'Several times a week', 'Once a week', 'Never', 'Rarely'],
      dtype=object)

In [226]:
nuevos_nombres_frecuencia_pod = {
    'Daily':'Diariamente',
    'Several times a week':'Varias veces por semana',
    'Once a week':'Una vez por semana',
    'Never':'Nunca',
    'Rarely':'Raramente'
}

Spotify_data['FRECUENCIA_POD'] = Spotify_data['FRECUENCIA_POD'].replace(nuevos_nombres_frecuencia_pod)

print(Spotify_data['FRECUENCIA_POD'].unique())
Spotify_data.head()

['Diariamente' 'Varias veces por semana' 'Una vez por semana' 'Nunca'
 'Raramente']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Si,Family Plan-Rs 179/month,Podcast,Melody,Noche,Tristeza,Tiempo libre,Listas de reproducción,3,Diariamente,Comedy,Interview,Both,Both,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Si,Individual Plan- Rs 119/ month,Podcast,Rap,Tarde,Reuniones Sociales,Entrenamiento,Listas de reproducción,2,Varias veces por semana,Comedy,Interview,Both,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Si,Student Plan-Rs 59/month,Podcast,Pop,Noche,Relajación,"Horas de estudio, Mientras viaja",Listas de reproducción,4,Una vez por semana,Sports,Interview,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,NaN,Music,Melody,Noche,"Relajación, Reuniones Sociales","Horario de oficina, Entrenamiento, Tiempo libre","Recomendaciones, Listas de reproducción",4,Nunca,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,NaN,Music,Melody,Noche,Relajación,Tiempo libre,"Recomendaciones, Listas de reproducción",4,Raramente,Lifestyle and Health,Story telling,Well known individuals,Both,Ok

In [227]:
Spotify_data["GENERO_FAV_POD"].nunique()

19

In [228]:
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Comedy", "Comedia", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Sports", "Deportes", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Lifestyle and Health", "Estilo de vida y salud", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Business", "Negocios", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Health and Fitness", "Salud y fitness", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Food and cooking", "Comida y cocina", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Everything", "De todo", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Informative stuff", "Contenido informativo", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Dance and Relevant cases", "Actualidad", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Technology", "Tecnología", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("General knowledge", "Cultura general", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Spiritual and devotional", "Espiritual", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Finance related and current affairs", "Finanzas y actualidad", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Murder Mystery", "Misterio y crímenes", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Political, informative, topics that interests me", "Política e información (temas de interés)", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Novels", "Novelas", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Self help", "Autoayuda", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Educational", "Educativo", regex=False)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.replace("Stories", "Historias", regex=False)

# Limpieza básica (espacios al final / principio)
Spotify_data["GENERO_FAV_POD"] = Spotify_data["GENERO_FAV_POD"].str.strip()

# Comprobar
print(Spotify_data["GENERO_FAV_POD"].unique())
print("Nº valores únicos:", Spotify_data["GENERO_FAV_POD"].nunique())
Spotify_data.head()

['Comedia' 'Deportes' nan 'Estilo de vida y salud' 'Negocios'
 'Salud y fitness' 'Comida y cocina' 'De todo' 'Contenido informativo'
 'Actualidad' 'Tecnología' 'Cultura general' 'Espiritual'
 'Finanzas y actualidad' 'Misterio y crímenes'
 'Política e información (temas de interés)' 'Novelas' 'Autoayuda'
 'Educativo' 'Historias']
Nº valores únicos: 19

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Si,Family Plan-Rs 179/month,Podcast,Melody,Noche,Tristeza,Tiempo libre,Listas de reproducción,3,Diariamente,Comedia,Interview,Both,Both,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Si,Individual Plan- Rs 119/ month,Podcast,Rap,Tarde,Reuniones Sociales,Entrenamiento,Listas de reproducción,2,Varias veces por semana,Comedia,Interview,Both,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Si,Student Plan-Rs 59/month,Podcast,Pop,Noche,Relajación,"Horas de estudio, Mientras viaja",Listas de reproducción,4,Una vez por semana,Deportes,Interview,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,NaN,Music,Melody,Noche,"Relajación, Reuniones Sociales","Horario de oficina, Entrenamiento, Tiempo libre","Recomendaciones, Listas de reproducción",4,Nunca,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,NaN,Music,Melody,Noche,Relajación,Tiempo libre,"Recomendaciones, Listas de reproducción",4,Raramente,Estilo de vida y salud,Story telling,Well known individuals,Both,Ok

In [229]:
Spotify_data["FORMATO_PREFERIDO_POD"].unique()

array(['Interview', nan, 'Story telling', 'Conversational', 'Educational'],
      dtype=object)

In [230]:
nuevos_nombres_formato = {
    'Interview':'Entrevista',
    'Story telling':'Relato',
    'Conversational':'Conversación',
    'Educational':'Educativo'
}

Spotify_data['FORMATO_PREFERIDO_POD'] = Spotify_data['FORMATO_PREFERIDO_POD'].replace(nuevos_nombres_formato)

print(Spotify_data['FORMATO_PREFERIDO_POD'].unique())
Spotify_data.head()

['Entrevista' nan 'Relato' 'Conversación' 'Educativo']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Si,Family Plan-Rs 179/month,Podcast,Melody,Noche,Tristeza,Tiempo libre,Listas de reproducción,3,Diariamente,Comedia,Entrevista,Both,Both,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Si,Individual Plan- Rs 119/ month,Podcast,Rap,Tarde,Reuniones Sociales,Entrenamiento,Listas de reproducción,2,Varias veces por semana,Comedia,Entrevista,Both,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Si,Student Plan-Rs 59/month,Podcast,Pop,Noche,Relajación,"Horas de estudio, Mientras viaja",Listas de reproducción,4,Una vez por semana,Deportes,Entrevista,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,NaN,Music,Melody,Noche,"Relajación, Reuniones Sociales","Horario de oficina, Entrenamiento, Tiempo libre","Recomendaciones, Listas de reproducción",4,Nunca,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,NaN,Music,Melody,Noche,Relajación,Tiempo libre,"Recomendaciones, Listas de reproducción",4,Raramente,Estilo de vida y salud,Relato,Well known individuals,Both,Ok

In [231]:
Spotify_data["PREFERENCIA_PRESENTADOR_POD"].unique()

array(['Both', nan, 'Well known individuals', 'unknown Podcasters'],
      dtype=object)

In [232]:
nuevos_nombres_presentador = {
    'Both':'Ambos',
    'Well known individuals':'Famoso',
    'unknown Podcasters':'Desconocido'
}

Spotify_data['PREFERENCIA_PRESENTADOR_POD'] = Spotify_data['PREFERENCIA_PRESENTADOR_POD'].replace(nuevos_nombres_presentador)

print(Spotify_data['PREFERENCIA_PRESENTADOR_POD'].unique())
Spotify_data.head()

['Ambos' nan 'Famoso' 'Desconocido']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Si,Family Plan-Rs 179/month,Podcast,Melody,Noche,Tristeza,Tiempo libre,Listas de reproducción,3,Diariamente,Comedia,Entrevista,Ambos,Both,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Si,Individual Plan- Rs 119/ month,Podcast,Rap,Tarde,Reuniones Sociales,Entrenamiento,Listas de reproducción,2,Varias veces por semana,Comedia,Entrevista,Ambos,NaN,Satisfied
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Si,Student Plan-Rs 59/month,Podcast,Pop,Noche,Relajación,"Horas de estudio, Mientras viaja",Listas de reproducción,4,Una vez por semana,Deportes,Entrevista,NaN,Both,Satisfied
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,NaN,Music,Melody,Noche,"Relajación, Reuniones Sociales","Horario de oficina, Entrenamiento, Tiempo libre","Recomendaciones, Listas de reproducción",4,Nunca,NaN,NaN,NaN,NaN,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,NaN,Music,Melody,Noche,Relajación,Tiempo libre,"Recomendaciones, Listas de reproducción",4,Raramente,Estilo de vida y salud,Relato,Famoso,Both,Ok

In [233]:
Spotify_data["PREFERENCIA_DURACION_POD"].unique()

array(['Both', nan, 'Longer', 'Shorter'], dtype=object)

In [258]:
nuevos_nombres_duracion = {
    'Both':'Ambos',
    'Longer':'Largo',
    'Shorter':'Corto'
}

Spotify_data['PREFERENCIA_DURACION_POD'] = Spotify_data['PREFERENCIA_DURACION_POD'].replace(nuevos_nombres_duracion)

print(Spotify_data['PREFERENCIA_DURACION_POD'].unique())
Spotify_data.head()

['Ambos' 'No aplicable/Ninguno' 'Largo' 'Corto']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,ESTADO_ANIMO,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Si,Family Plan-Rs 179/month,Podcast,Melody,Noche,Tristeza,Tiempo libre,Listas de reproducción,3,Diariamente,Comedia,Entrevista,Ambos,Ambos,Ok
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Si,Individual Plan- Rs 119/ month,Podcast,Rap,Tarde,Reuniones Sociales,Entrenamiento,Listas de reproducción,2,Varias veces por semana,Comedia,Entrevista,Ambos,No aplicable/Ninguno,Satisfecho
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Si,Student Plan-Rs 59/month,Podcast,Pop,Noche,Relajación,"Horas de estudio, Mientras viaja",Listas de reproducción,4,Una vez por semana,Deportes,Entrevista,No aplicable/Ninguno,Ambos,Satisfecho
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,No aplicable/Ninguno,Music,Melody,Noche,"Relajación, Reuniones Sociales","Horario de oficina, Entrenamiento, Tiempo libre","Recomendaciones, Listas de reproducción",4,Nunca,No aplicable/Ninguno,No aplicable/Ninguno,No aplicable/Ninguno,No aplicable/Ninguno,Ok
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,No aplicable/Ninguno,Music,Melody,Noche,Relajación,Tiempo libre,"Recomendaciones, Listas de reproducción",4,Raramente,Estilo de vida y salud,Relato,Famoso,Ambos,Ok

In [235]:
Spotify_data["SATISFACCION_POD"].unique()

array(['Ok', 'Satisfied', 'Very Satisfied', 'Very Dissatisfied',
       'Dissatisfied'], dtype=object)

In [316]:
nuevos_nombres_satisfaccion = {
    'Satisfied':'Satisfecho',
    'Very Satisfied':'Muy satisfecho',
    'Very Dissatisfied':'Muy insatisfecho',
    'Dissatisfied':'Insatisfecho'
}

Spotify_data['SATISFACCION_POD'] = Spotify_data['SATISFACCION_POD'].replace(nuevos_nombres_satisfaccion)

print(Spotify_data['SATISFACCION_POD'].unique())
Spotify_data.head()

['Ok' 'Satisfecho' 'Muy satisfecho' 'Muy insatisfecho' 'Insatisfecho']

,EDAD,GENERO,ANTIGUEDAD,DISPOSITIVO,SUSCRIPCION,QUIERE_PREMIUM,PREMIUM_PREFERIDO,CONTENIDO_PREFERIDO,GENERO_FAV_MUSICA,FRANJA_HORARIA,...,MOMENTO_MUSICA,DESCUBRIMIENTO,VALORACION_RECOMENDACIONES,FRECUENCIA_POD,GENERO_FAV_POD,FORMATO_PREFERIDO_POD,PREFERENCIA_PRESENTADOR_POD,PREFERENCIA_DURACION_POD,SATISFACCION_POD,CANTIDAD_DISPOSITIVOS
0,20-35,Mujer,Más de 2 años,Altavoz Inteligente,Free,Si,Family Plan-Rs 179/month,Podcast,Melody,Noche,...,Tiempo libre,Listas de reproducción,3,Diariamente,Comedia,Entrevista,Ambos,Ambos,Ok,1
1,12-20,Hombre,Más de 2 años,Ordenador,Free,Si,Individual Plan- Rs 119/ month,Podcast,Rap,Tarde,...,Entrenamiento,Listas de reproducción,2,Varias veces por semana,Comedia,Entrevista,Ambos,No aplicable/Ninguno,Satisfecho,1
2,35-60,Otro,De 6 meses a 1 año,Altavoz Inteligente,Free,Si,Student Plan-Rs 59/month,Podcast,Pop,Noche,...,"Horas de estudio, Mientras viaja",Listas de reproducción,4,Una vez por semana,Deportes,Entrevista,No aplicable/Ninguno,Ambos,Satisfecho,1
3,20-35,Mujer,De 1 año a 2 años,"Smartphone, Altavoz Inteligente",Free,No,No aplicable/Ninguno,Music,Melody,Noche,...,"Horario de oficina, Entrenamiento, Tiempo libre","Recomendaciones, Listas de reproducción",4,Nunca,No aplicable/Ninguno,No aplicable/Ninguno,No aplicable/Ninguno,No aplicable/Ninguno,Ok,2
4,20-35,Mujer,De 1 año a 2 años,Smartphone,Free,No,No aplicable/Ninguno,Music,Melody,Noche,...,Tiempo libre,"Recomendaciones, Listas de reproducción",4,Raramente,Estilo de vida y salud,Relato,Famoso,Ambos,Ok,1

In [ ]:
***************************************************************************************************************

In [239]:
CONTEO_DISPOSITIVO = Spotify_data["DISPOSITIVO"].str.split(', ').explode().value_counts()
CONTEO_DISPOSITIVO

DISPOSITIVO
Smartphone                          391
Ordenador                           144
Altavoz Inteligente                  92
Dispositivo Portatil Inteligente     44
Name: count, dtype: int64

In [240]:
#Valores únicos de estado de ánimo.
CONTEO_ESTADO_ANIMO = Spotify_data["ESTADO_ANIMO"].str.split(', ').explode().value_counts()
CONTEO_ESTADO_ANIMO

ESTADO_ANIMO
Relajación            364
Motivador             199
Tristeza              167
Reuniones Sociales     92
Name: count, dtype: int64

In [241]:
#Valores únicos de momento música
df_split = Spotify_data["MOMENTO_MUSICA"].str.split(',', expand=True).stack()

CONTEO_MOMENTO_MUSICA = df_split.str.strip().value_counts()

CONTEO_MOMENTO_MUSICA = CONTEO_MOMENTO_MUSICA[CONTEO_MOMENTO_MUSICA.index != ""]

print(CONTEO_MOMENTO_MUSICA)

Mientras viaja        331
Tiempo libre          263
Entrenamiento         153
Horario de oficina     87
Horas de estudio       85
Reuniones sociales      1
Por la noche            1
Cocinando               1
Aleatorio               1
Antes de dormir         1
Name: count, dtype: int64

In [242]:
#Valores únicos de descubrimiento.
CONTEO_DESCUBRIMIENTO = Spotify_data["DESCUBRIMIENTO"].str.split(', ').explode().value_counts()
CONTEO_DESCUBRIMIENTO

DESCUBRIMIENTO
Listas de reproducción    264
Recomendaciones           258
Otros                     120
Radio                     107
Redes sociales              3
Recomendaciones,Otros       1
Amigos                      1
Búsqueda                    1
Name: count, dtype: int64

In [243]:
#Valores únicos de género favorido de podcast.
CONTEO_GENERO_FAV_POD = Spotify_data["GENERO_FAV_POD"].str.split(', ').explode().value_counts()
CONTEO_GENERO_FAV_POD

GENERO_FAV_POD
Comedia                                      107
Estilo de vida y salud                       102
Salud y fitness                               78
Deportes                                      51
Comida y cocina                               20
Finanzas y actualidad                          1
Educativo                                      1
Autoayuda                                      1
Novelas                                        1
Política e información (temas de interés)      1
Misterio y crímenes                            1
Tecnología                                     1
Espiritual                                     1
Cultura general                                1
Actualidad                                     1
Contenido informativo                          1
De todo                                        1
Negocios                                       1
Historias                                      1
Name: count, dtype: int64

In [ ]:
**************************************************************************************************************

In [244]:
print(Spotify_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   EDAD                         520 non-null    object
 1   GENERO                       520 non-null    object
 2   ANTIGUEDAD                   520 non-null    object
 3   DISPOSITIVO                  520 non-null    object
 4   SUSCRIPCION                  520 non-null    object
 5   QUIERE_PREMIUM               520 non-null    object
 6   PREMIUM_PREFERIDO            312 non-null    object
 7   CONTENIDO_PREFERIDO          520 non-null    object
 8   GENERO_FAV_MUSICA            520 non-null    object
 9   FRANJA_HORARIA               520 non-null    object
 10  ESTADO_ANIMO                 520 non-null    object
 11  MOMENTO_MUSICA               520 non-null    object
 12  DESCUBRIMIENTO               520 non-null    object
 13  VALORACION_RECOMENDACIONES   520 non-null    int64
 14  FRECUENCIA_POD               520 non-null    object
 15  GENERO_FAV_POD               372 non-null    object
 16  FORMATO_PREFERIDO_POD        380 non-null    object
 17  PREFERENCIA_PRESENTADOR_POD  379 non-null    object
 18  PREFERENCIA_DURACION_POD     391 non-null    object
 19  SATISFACCION_POD             520 non-null    object
dtypes: int64(1), object(19)
memory usage: 81.4+ KB
None

In [245]:
#Relleno los valores faltantes de con 'No aplicable/Ninguno'(la ausencia de interés)
#Esos usuarios son valiosos porque nos dicen cómo se comporta alguien que solo escucha música. 
#Al etiquetarlos como 'No Aplicable', permito que el modelo de Machine Learning aprenda la diferencia entre un melómano puro y un oyente mixto.

cols_podcasts = [
    'PREMIUM_PREFERIDO', 
    'GENERO_FAV_POD', 
    'FORMATO_PREFERIDO_POD', 
    'PREFERENCIA_PRESENTADOR_POD',
    'PREFERENCIA_DURACION_POD' 
]

for col in cols_podcasts:
    Spotify_data[col] = Spotify_data[col].fillna('No aplicable/Ninguno')
print(Spotify_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   EDAD                         520 non-null    object
 1   GENERO                       520 non-null    object
 2   ANTIGUEDAD                   520 non-null    object
 3   DISPOSITIVO                  520 non-null    object
 4   SUSCRIPCION                  520 non-null    object
 5   QUIERE_PREMIUM               520 non-null    object
 6   PREMIUM_PREFERIDO            520 non-null    object
 7   CONTENIDO_PREFERIDO          520 non-null    object
 8   GENERO_FAV_MUSICA            520 non-null    object
 9   FRANJA_HORARIA               520 non-null    object
 10  ESTADO_ANIMO                 520 non-null    object
 11  MOMENTO_MUSICA               520 non-null    object
 12  DESCUBRIMIENTO               520 non-null    object
 13  VALORACION_RECOMENDACIONES   520 non-null    int64
 14  FRECUENCIA_POD               520 non-null    object
 15  GENERO_FAV_POD               520 non-null    object
 16  FORMATO_PREFERIDO_POD        520 non-null    object
 17  PREFERENCIA_PRESENTADOR_POD  520 non-null    object
 18  PREFERENCIA_DURACION_POD     520 non-null    object
 19  SATISFACCION_POD             520 non-null    object
dtypes: int64(1), object(19)
memory usage: 81.4+ KB
None

In [246]:
print(Spotify_data.describe())

       VALORACION_RECOMENDACIONES
count                  520.000000
mean                     3.503846
std                      0.979552
min                      1.000000
25%                      3.000000
50%                      3.500000
75%                      4.000000
max                      5.000000

In [247]:
print(Spotify_data.isnull().sum())

EDAD                           0
GENERO                         0
ANTIGUEDAD                     0
DISPOSITIVO                    0
SUSCRIPCION                    0
QUIERE_PREMIUM                 0
PREMIUM_PREFERIDO              0
CONTENIDO_PREFERIDO            0
GENERO_FAV_MUSICA              0
FRANJA_HORARIA                 0
ESTADO_ANIMO                   0
MOMENTO_MUSICA                 0
DESCUBRIMIENTO                 0
VALORACION_RECOMENDACIONES     0
FRECUENCIA_POD                 0
GENERO_FAV_POD                 0
FORMATO_PREFERIDO_POD          0
PREFERENCIA_PRESENTADOR_POD    0
PREFERENCIA_DURACION_POD       0
SATISFACCION_POD               0
dtype: int64

In [323]:
Spotify_data.to_csv('Spotify_data_total.csv', index=False)
print("✅ Archivo 'Spotify_data_total.csv' guardado. Ya puedes descargarlo o usarlo en otra página.")

✅ Archivo 'Spotify_data_total.csv' guardado. Ya puedes descargarlo o usarlo en otra página.

In [ ]:
*****************************************************************************************************************************